# Generated by Django 4.0.6 on 2022-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_store_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media')),
                ('address', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('admitDate', models.DateField(null=True)),
            ],
        ),
    ]
