# Generated by Django 4.0.6 on 2022-07-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0006_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeapp.product'),
        ),
    ]
