# Generated by Django 4.0.6 on 2022-07-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0007_store_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='quantiy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
